---
title: "Beta Distribution Graphics"
output:
  html_document:
    df_print: paged
runtime: shiny
---


```{r echo=FALSE}
library(shiny)
library(ggplot2)
```

```{r echo=FALSE}
ui <- navbarPage("My Application",
  tabPanel("Component 1"),
  tabPanel("Component 2"),
  tabPanel("Component 3")
)
```


```{r echo=FALSE}
# Basic input functions for beta dist.
ui <- fluidPage(theme = 'bootstrap.css',
  titlePanel("Basic Beta Sampling"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput(inputId = "alpha", 
                  label = "Choose alpha :", 
                  value = 1, 
                  min = 0.1, 
                  max = 100, 
                  step = 0.1),
      sliderInput(inputId = "beta", 
                  label = "Choose beta :", 
                  value = 1, 
                  min = 0.1, 
                  max = 100, 
                  step = 0.1),
      sliderInput(inputId = "N", 
                  label = "Choose sample size N :", 
                  value = 5000, 
                  min = 10, 
                  max = 10000, 
                  step = 1)     
    ),
    mainPanel(
      plotOutput('hist')
    )
  )
  
)

server <- function(input, output) {
  output$hist <- renderPlot({
    title<- "Beta Distribution with N samples"
    hist(rbeta(input$N,input$alpha,input$beta),
               xlab = "X",
               main = title,
               breaks = 100)
  })
}

shinyApp(ui = ui, server = server)
```

```{r echo=FALSE}
# beta dist with input alpha and beta. ggplot. showing alpha and beta values interactively.
ui <- fluidPage(
  titlePanel('Beta Distributions with a,b'),
  sidebarLayout(
    sidebarPanel(sliderInput(inputId = "alpha", 
                  label = "Choose alpha :", 
                  value = 1, 
                  min = 0.1, 
                  max = 100, 
                  step = 0.1),
                 sliderInput(inputId = "beta", 
                  label = "Choose beta :", 
                  value = 1, 
                  min = 0.1, 
                  max = 100, 
                  step = 0.1)),
    mainPanel(plotOutput('dist'))
  )
)

server <- function(input, output) {
  output$dist <- renderPlot({
    alpha <-input$alpha
    beta <-input$beta 
    p <- seq(0,1,length = 1000)
    db <- dbeta(p,alpha,beta)
    ggplot() + 
      geom_line(aes(p,db)) + 
      ggtitle("Beta Distribution") + 
      xlab("probability") + 
      ylab('density') + 
      theme(plot.title = element_text(size = 14, face = "bold",hjust = 0.5), 
            axis.title = element_text(size = 10, face = 'bold'))
  })
}

shinyApp(ui = ui, server = server)
```

```{r echo=FALSE}
# Beta sample dist with input w and k
ui <- fluidPage(
  titlePanel("Beta Sampling with w,k"),
  sidebarLayout(
    sidebarPanel(
      sliderInput(inputId = "w", 
                  label = "Choose the most likely possibility :", 
                  value = 0.01, 
                  min = 0.01, 
                  max = 1, 
                  step = 0.01),
  sliderInput(inputId = "k", 
              label = "Choose the k value :", 
              value = 2.001, 
              min = 2, 
              max = 1000, 
              step = 1)
    ),
    mainPanel(
      plotOutput('hist')
    )
  )
)

server <- function(input, output) {
  output$hist <- renderPlot({
    alpha <-input$w*(input$k - 2) +1
    beta <- (1-input$w)*(input$k -2) +1
    title<- "Beta Distribution with 100000 samples"
    hist(rbeta(100000,alpha,beta),
         main = title,
         xlab = 'X',
         breaks = 100)
  })
}

shinyApp(ui = ui, server = server)
```

```{r echo=FALSE, include=FALSE}
# beta dist with input w and k
ui <- fluidPage(
  sliderInput(inputId = "w", label = "Choose the most likely possibility :", value = 0.01, min = 0.01, max = 1, step = 0.01),
  sliderInput(inputId = "k", label = "Choose the k value :", value = 2.001, min = 2, max = 1000, step = 1),
  plotOutput('dist')
)

server <- function(input, output) {
  output$dist <- renderPlot({
    alpha <-input$w*(input$k - 2) +1
    beta <- (1-input$w)*(input$k -2) +1
    title<- "Beta Distribution"
    p = seq(0,1,length = 100)
    plot(p, dbeta(p,alpha,beta),ylab='density',type='l')
  })
}

shinyApp(ui = ui, server = server)
```

```{r echo=FALSE}
# beta dist with input w and k. ggplot. showing alpha and beta values interactively.
ui <- fluidPage(
  titlePanel('Beta Distributions with w,k'),
  sidebarLayout(
    sidebarPanel(sliderInput(inputId = "w", label = "Choose the most likely possibility(w ; mode) :", value = 0.01, min = 0.01, max = 1, step = 0.01),
  sliderInput(inputId = "k", label = "Choose the k value :", value = 2.001, min = 2, max = 50, step = 1)),
    mainPanel(plotOutput('dist'))
  )
)

server <- function(input, output) {
  output$dist <- renderPlot({
    alpha <-input$w*(input$k - 2) +1
    beta <- (1-input$w)*(input$k -2) +1
    p <- seq(0,1,length = 1000)
    db <- dbeta(p,alpha,beta)
    ggplot() + geom_line(aes(p,db)) + ggtitle("Beta Distribution") + xlab("probability") + ylab('density') + theme(plot.title = element_text(size = 14, face = "bold",hjust = 0.5), axis.title = element_text(size = 10, face = 'bold'))
  })
  output$abvalue <- renderText({
    paste("alpha =", input$w*(input$k - 2) +1,
    "beta = ", (1-input$w)*(input$k -2) +1)
    
  })
}

shinyApp(ui = ui, server = server)
```